version: '3.3'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./dockerfiles/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_DATABASE: server-management
      MONGO_INITDB_ROOT_PASSWORD: m6yzysH6DT
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/configdb
#      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      # - ./dockerfiles/mongo/my.cnf:/etc/mongo/my.cnf

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/var/www
      - ./dockerfiles/nginx/conf.d/:/etc/nginx/conf.d
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8080:80
